# Dataset configurations for Unifill

# Debug mode (false by default)
debug: false

# Alias sources to use when processing Unicode data
# Available sources: formal_aliases, informative_aliases, cldr_annotations
alias-sources:
  - cldr_annotations

# Unicode blocks with their code point ranges
unicode-blocks:
  # Basic Latin (ASCII): U+0000 to U+007F (128 characters)
  "Basic Latin": [0x0000, 0x0080]
  # Latin-1 Supplement: U+0080 to U+00FF (128 characters)
  "Latin-1 Supplement": [0x0080, 0x0100]
  # Latin Extended-A: U+0100 to U+017F (128 characters)
  "Latin Extended-A": [0x0100, 0x0180]
  # Latin Extended-B: U+0180 to U+024F (208 characters)
  "Latin Extended-B": [0x0180, 0x0250]
  # IPA Extensions: U+0250 to U+02AF (96 characters)
  "IPA Extensions": [0x0250, 0x02B0]
  # Spacing Modifier Letters: U+02B0 to U+02FF (80 characters)
  "Spacing Modifier Letters": [0x02B0, 0x0300]
  # Combining Diacritical Marks: U+0300 to U+036F (112 characters)
  "Combining Diacritical Marks": [0x0300, 0x0370]
  # Greek and Coptic: U+0370 to U+03FF (135 characters)
  "Greek and Coptic": [0x0370, 0x0400]
  # Cyrillic: U+0400 to U+04FF (not in every-day dataset)
  "Cyrillic": [0x0400, 0x0500]
  # Currency Symbols: U+20A0 to U+20CF (31 characters)
  "Currency Symbols": [0x20A0, 0x20D0]
  # Combining Diacriticals for Symbols: U+20D0 to U+20FF (33 characters)
  "Combining Diacriticals for Symbols": [0x20D0, 0x2100]
  # Letterlike Symbols: U+2100 to U+214F (80 characters)
  "Letterlike Symbols": [0x2100, 0x2150]
  # Number Forms: U+2150 to U+218F (60 characters)
  "Number Forms": [0x2150, 0x2190]
  # Arrows: U+2190 to U+21FF (112 characters)
  "Arrows": [0x2190, 0x2200]
  # Mathematical Operators: U+2200 to U+22FF (256 characters)
  "Mathematical Operators": [0x2200, 0x2300]
  # Miscellaneous Technical: U+2300 to U+23FF (251 characters)
  "Miscellaneous Technical": [0x2300, 0x2400]
  # Control Pictures: U+2400 to U+243F (39 characters)
  "Control Pictures": [0x2400, 0x2440]
  # Enclosed Alphanumerics: U+2460 to U+24FF (160 characters)
  "Enclosed Alphanumerics": [0x2460, 0x2500]
  # Box Drawing: U+2500 to U+257F (128 characters)
  "Box Drawing": [0x2500, 0x2580]
  # Block Elements: U+2580 to U+259F (32 characters)
  "Block Elements": [0x2580, 0x25A0]
  # Geometric Shapes: U+25A0 to U+25FF (96 characters)
  "Geometric Shapes": [0x25A0, 0x2600]
  # Miscellaneous Symbols: U+2600 to U+26FF (256 characters)
  "Miscellaneous Symbols": [0x2600, 0x2700]
  # Dingbats: U+2700 to U+27BF (192 characters)
  "Dingbats": [0x2700, 0x27C0]
  # Misc Mathematical Symbols-A: U+27C0 to U+27EF (48 characters)
  "Misc Mathematical Symbols-A": [0x27C0, 0x27F0]
  # Supplemental Arrows-A: U+27F0 to U+27FF (16 characters)
  "Supplemental Arrows-A": [0x27F0, 0x2800]
  # Supplemental Arrows-B: U+2900 to U+297F (128 characters)
  "Supplemental Arrows-B": [0x2900, 0x2980]
  # Misc Mathematical Symbols-B: U+2980 to U+29FF (128 characters)
  "Misc Mathematical Symbols-B": [0x2980, 0x2A00]
  # Supplemental Math Operators: U+2A00 to U+2AFF (256 characters)
  "Supplemental Math Operators": [0x2A00, 0x2B00]
  # Misc Symbols and Arrows: U+2B00 to U+2BFF (206 characters)
  "Misc Symbols and Arrows": [0x2B00, 0x2C00]
  # Alphabetic Presentation Forms: U+FB00 to U+FB4F (58 characters)
  "Alphabetic Presentation Forms": [0xFB00, 0xFB50]
  # Variation Selectors: U+FE00 to U+FE0F (16 characters)
  "Variation Selectors": [0xFE00, 0xFE10]
  # Vertical Forms: U+FE10 to U+FE1F (10 characters)
  "Vertical Forms": [0xFE10, 0xFE20]
  # Combining Half Marks: U+FE20 to U+FE2F (16 characters)
  "Combining Half Marks": [0xFE20, 0xFE30]
  # Halfwidth and Fullwidth Forms: U+FF00 to U+FFEF (225 characters)
  "Halfwidth and Fullwidth Forms": [0xFF00, 0xFFF0]
  # Ancient Greek Numbers: U+10140 to U+1018F (77 characters)
  "Ancient Greek Numbers": [0x10140, 0x10190]
  # Ancient Symbols: U+10190 to U+101CF (13 characters)
  "Ancient Symbols": [0x10190, 0x101D0]
  # Musical Symbols: U+1D100 to U+1D1FF (231 characters)
  "Musical Symbols": [0x1D100, 0x1D200]
  # Ancient Greek Musical Notation: U+1D200 to U+1D24F (70 characters)
  "Ancient Greek Musical Notation": [0x1D200, 0x1D250]
  # Mathematical Alphanumeric Symbols: U+1D400 to U+1D7FF (996 characters)
  "Mathematical Alphanumeric Symbols": [0x1D400, 0x1D800]
  # Arabic Mathematical Alphabetic Symbols: U+1EE00 to U+1EEFF (143 characters)
  "Arabic Mathematical Alphabetic Symbols": [0x1EE00, 0x1EF00]
  # Misc Symbols and Pictographs: U+1F300 to U+1F5FF (766 characters)
  "Misc Symbols and Pictographs": [0x1F300, 0x1F600]
  # Emoticons: U+1F600 to U+1F64F (80 characters)
  "Emoticons": [0x1F600, 0x1F650]
  # Ornamental Dingbats: U+1F650 to U+1F67F (48 characters)
  "Ornamental Dingbats": [0x1F650, 0x1F680]
  # Transport and Map Symbols: U+1F680 to U+1F6FF (98 characters)
  "Transport and Map Symbols": [0x1F680, 0x1F700]
  # Geometric Shapes Extended: U+1F780 to U+1F7FF (85 characters)
  "Geometric Shapes Extended": [0x1F780, 0x1F800]
  # Supplemental Arrows-C: U+1F800 to U+1F8FF (148 characters)
  "Supplemental Arrows-C": [0x1F800, 0x1F900]
  # Supplemental Symbols and Pictographs: U+1F900 to U+1F9FF (15 characters)
  "Supplemental Symbols and Pictographs": [0x1F900, 0x1FA00]

datasets:
  # Every-day dataset with common Unicode blocks (6975 characters)
  every-day:
    - Basic Latin
    - Latin-1 Supplement
    - Latin Extended-A
    - Latin Extended-B
    - IPA Extensions
    - Spacing Modifier Letters
    - Combining Diacritical Marks
    - Greek and Coptic
    - Currency Symbols
    - Combining Diacriticals for Symbols
    - Letterlike Symbols
    - Number Forms
    - Arrows
    - Mathematical Operators
    - Miscellaneous Technical
    - Control Pictures
    - Enclosed Alphanumerics
    - Box Drawing
    - Block Elements
    - Geometric Shapes
    - Miscellaneous Symbols
    - Dingbats
    - Misc Mathematical Symbols-A
    - Supplemental Arrows-A
    - Supplemental Arrows-B
    - Misc Mathematical Symbols-B
    - Supplemental Math Operators
    - Misc Symbols and Arrows
    - Alphabetic Presentation Forms
    - Variation Selectors
    - Vertical Forms
    - Combining Half Marks
    - Halfwidth and Fullwidth Forms
    - Ancient Greek Numbers
    - Ancient Symbols
    - Musical Symbols
    - Ancient Greek Musical Notation
    - Mathematical Alphanumeric Symbols
    - Arabic Mathematical Alphabetic Symbols
    - Misc Symbols and Pictographs
    - Emoticons
    - Ornamental Dingbats
    - Transport and Map Symbols
    - Geometric Shapes Extended
    - Supplemental Arrows-C
    - Supplemental Symbols and Pictographs

  # Complete dataset with all Unicode blocks
  complete:
    - all # Special value to include all Unicode blocks
